#cloud-config

yum_repos:
  ${mongodb_package}-${mongodb_version}:
    name: MongoDB Repository
    baseurl: https://${repo_url}/yum/amazon/2/${mongodb_package}/${mongodb_version}/$basearch/
    enabled: true
    gpgcheck: true
    gpgkey: https://www.mongodb.org/static/pgp/server-${mongodb_version}.asc

package_update: true
packages:
  - jq
  - ${mongodb_package}

fqdn: ${fqdn}
preserve_hostname: false

final_message: "Cloud Init complete!"